services:
  news-reader:
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: news-reader
    volumes:
      - /opt/newsnek:/app/data
    environment:
      - INTERVAL=60
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["python3", "nwsreader.py", "--file", "sources.txt", "--overview", "--interval", "60"]
