services:
  news-reader:
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: news-reader
    volumes:
      - /opt/newssnek/data:/app/data
      - /opt/newssnek:/opt/config
    environment:
      - INTERVAL=${INTERVAL}
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["python3", "nwsreader.py", "--file", "sources.txt", "--overview"]
